openapi: 3.0.0
info:
  title: (title)
  version: 0.0.0
tags:
  - name: blog
  - name: article
paths:
  /articles:
    get:
      operationId: listArticles
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListArticles'
      tags:
        - article
  /articles/{id}:
    get:
      operationId: readArticle
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArticleResponse'
      tags:
        - article
  /blogs:
    post:
      operationId: createBlog
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Blog'
      tags:
        - blog
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                dto:
                  $ref: '#/components/schemas/CreateBlogContent'
              required:
                - dto
    get:
      operationId: resourceReadBlogs
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                required:
                  - currentPage
                  - perPage
                  - totalCount
                  - items
                properties:
                  currentPage:
                    type: integer
                    format: uint64
                  perPage:
                    type: integer
                    format: uint64
                  totalCount:
                    type: integer
                    format: uint64
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Blog'
      tags:
        - blog
components:
  schemas:
    Article:
      type: object
      required:
        - id
        - title
        - body
        - created_at
        - updated_at
      properties:
        id:
          type: integer
        title:
          type: string
        body:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
      description: |-
        Generated by scaffdog
        feature name is article
        created at 2024/10/29
    ArticleResponse:
      type: object
      required:
        - article
      properties:
        article:
          $ref: '#/components/schemas/Article'
    Blog:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: uint64
          readOnly: true
    CreateBlogContent:
      type: object
      required:
        - title
      properties:
        title:
          $ref: '#/components/schemas/blogTitle'
    ListArticles:
      type: object
      required:
        - items
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Article'
    blogTitle:
      type: string
      minLength: 1
      maxLength: 255
    uuidv4:
      type: string
      format: uuid
