openapi: 3.0.0
info:
  title: (title)
  version: 0.0.0
tags:
  - name: blog
  - name: article
paths:
  /articles:
    get:
      operationId: listArticles
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                required:
                  - items
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Article'
      tags:
        - article
    post:
      operationId: createArticle
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                required:
                  - article
                properties:
                  article:
                    $ref: '#/components/schemas/Article'
      tags:
        - article
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                dto:
                  $ref: '#/components/schemas/ArticleOperation.CreateArticleDTO'
              required:
                - dto
  /articles/{id}:
    get:
      operationId: readArticle
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                required:
                  - article
                properties:
                  article:
                    $ref: '#/components/schemas/Article'
        '404':
          description: The server cannot find the requested resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArticleOperation.NotFoundArticle'
      tags:
        - article
    put:
      operationId: updateArticle
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                required:
                  - article
                properties:
                  article:
                    $ref: '#/components/schemas/Article'
        '404':
          description: The server cannot find the requested resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArticleOperation.NotFoundArticle'
      tags:
        - article
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ArticleOperation.UpdateArticleDTO'
  /blogs:
    post:
      operationId: createBlog
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Blog'
      tags:
        - blog
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                dto:
                  $ref: '#/components/schemas/CreateBlogContent'
              required:
                - dto
    get:
      operationId: resourceReadBlogs
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                required:
                  - currentPage
                  - perPage
                  - totalCount
                  - items
                properties:
                  currentPage:
                    type: integer
                    format: uint64
                  perPage:
                    type: integer
                    format: uint64
                  totalCount:
                    type: integer
                    format: uint64
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Blog'
      tags:
        - blog
components:
  schemas:
    Article:
      type: object
      required:
        - id
        - title
        - body
      properties:
        id:
          type: integer
        title:
          $ref: '#/components/schemas/ArticleTitle'
        body:
          $ref: '#/components/schemas/ArticleBody'
      description: |-
        Generated by scaffdog
        feature name is article
        created at 2024/10/29
    ArticleBody:
      type: string
      minLength: 10
    ArticleOperation.CreateArticleDTO:
      type: object
      required:
        - title
        - body
      properties:
        title:
          $ref: '#/components/schemas/ArticleTitle'
        body:
          $ref: '#/components/schemas/ArticleBody'
    ArticleOperation.NotFoundArticle:
      type: object
    ArticleOperation.UpdateArticleDTO:
      type: object
      required:
        - title
        - body
      properties:
        title:
          $ref: '#/components/schemas/ArticleTitle'
        body:
          $ref: '#/components/schemas/ArticleBody'
    ArticleTitle:
      type: string
      minLength: 1
      maxLength: 255
    Blog:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: uint64
          readOnly: true
    CreateBlogContent:
      type: object
      required:
        - title
      properties:
        title:
          $ref: '#/components/schemas/blogTitle'
    blogTitle:
      type: string
      minLength: 1
      maxLength: 255
    uuidv4:
      type: string
      format: uuid
